// ============================================================
// CUSTOM PROGRAM STORE
// Stores a user's personalized training program generated by
// Zaki after onboarding. Overrides the hardcoded default when
// present.
// ============================================================
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { ProgramExercise, SessionType } from './training-program';
import { applyScheduleWithHistory, buildFullSchedule, type DayName } from './schedule-store';
import { PROGRAM_SESSIONS } from './training-program';

const CUSTOM_PROGRAM_KEY = '@custom_program_v1';

// ── Types ────────────────────────────────────────────────────

export interface CustomProgram {
  /** Human-readable program name, e.g. "Beginner Full Body 3x/week" */
  name: string;
  /** Description of the program */
  description: string;
  /** Session definitions — maps session IDs to exercise lists */
  sessions: Record<string, ProgramExercise[]>;
  /** Session display names */
  sessionNames: Record<string, string>;
  /** Session colors */
  sessionColors: Record<string, string>;
  /** Weekly schedule — maps day names to session IDs */
  weeklySchedule: Record<string, string>;
  /** Nutrition targets */
  nutritionTargets?: {
    training: { calories: number; protein: number; fat: number; carbs: number };
    rest: { calories: number; protein: number; fat: number; carbs: number };
  };
  /** ISO timestamp when this program was generated */
  createdAt: string;
  /** Whether Zaki generated this */
  generatedByZaki: boolean;
  /** Duration of the program in weeks (default 4 for starter programs) */
  durationWeeks?: number;
  /** ISO timestamp when the program was completed (auto-set by progression logic) */
  completedAt?: string;
}

// ── Storage API ──────────────────────────────────────────────

export async function loadCustomProgram(): Promise<CustomProgram | null> {
  try {
    const raw = await AsyncStorage.getItem(CUSTOM_PROGRAM_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as CustomProgram;
  } catch {
    return null;
  }
}

export async function saveCustomProgram(program: CustomProgram): Promise<void> {
  await AsyncStorage.setItem(CUSTOM_PROGRAM_KEY, JSON.stringify(program));
}

export async function clearCustomProgram(): Promise<void> {
  await AsyncStorage.removeItem(CUSTOM_PROGRAM_KEY);
}

// ── Helpers ──────────────────────────────────────────────────

/**
 * Get exercises for a session type, checking custom program first,
 * then falling back to the hardcoded default.
 */
export async function getSessionExercises(sessionType: string): Promise<ProgramExercise[]> {
  const custom = await loadCustomProgram();
  if (custom?.sessions?.[sessionType]) {
    return custom.sessions[sessionType];
  }
  // Fall back to default
  const defaultKey = sessionType as keyof typeof PROGRAM_SESSIONS;
  return PROGRAM_SESSIONS[defaultKey] ?? [];
}

/**
 * Get session display name, checking custom program first.
 */
export async function getSessionDisplayName(sessionType: string): Promise<string> {
  const custom = await loadCustomProgram();
  if (custom?.sessionNames?.[sessionType]) {
    return custom.sessionNames[sessionType];
  }
  // Fall back to default names
  const defaultNames: Record<string, string> = {
    'upper-a': 'Upper A — Strength',
    'lower-a': 'Lower A — Strength',
    'upper-b': 'Upper B — Volume',
    'lower-b': 'Lower B — Volume',
    rest: 'Rest Day',
  };
  return defaultNames[sessionType] ?? sessionType;
}

// ── Program Templates ────────────────────────────────────────
// Pre-built program templates for common goals/levels.
// Zaki can also generate fully custom programs via AI.

const SESSION_COLORS_POOL = [
  '#3B82F6', '#8B5CF6', '#06B6D4', '#10B981', '#F59E0B', '#EF4444',
];

export interface ProgramTemplate {
  id: string;
  name: string;
  description: string;
  daysPerWeek: number;
  goal: string;
  experience: string;
  equipment: string;
  sessions: Record<string, ProgramExercise[]>;
  sessionNames: Record<string, string>;
  weeklySchedule: Record<string, string>;
}

// ── Beginner Full Body 3x/week ──
const BEGINNER_FULL_BODY: ProgramTemplate = {
  id: 'beginner-full-body-3x',
  name: 'Full Body 3x/Week',
  description: 'Perfect for beginners — 3 full-body sessions per week with compound movements',
  daysPerWeek: 3,
  goal: 'muscle_gain',
  experience: 'beginner',
  equipment: 'full_gym',
  sessions: {
    'full-a': [
      { name: 'Barbell Back Squat', sets: 3, repsMin: 8, repsMax: 10, restSeconds: 150, notes: 'Below parallel', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Barbell Bench Press', sets: 3, repsMin: 8, repsMax: 10, restSeconds: 150, notes: 'Touch chest', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'Barbell Row', sets: 3, repsMin: 8, repsMax: 10, restSeconds: 120, notes: 'Pull to navel', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'DB Overhead Press', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 90, notes: 'Seated or standing', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'compound' },
      { name: 'DB Bicep Curl', sets: 2, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Controlled tempo', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
      { name: 'Tricep Rope Pushdown', sets: 2, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Split at bottom', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
    ],
    'full-b': [
      { name: 'Romanian Deadlift', sets: 3, repsMin: 8, repsMax: 10, restSeconds: 150, notes: 'Feel hamstring stretch', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Incline DB Press', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 120, notes: '30° angle', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'Wide-Grip Lat Pulldown', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 120, notes: 'Pull to upper chest', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'Leg Press', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 120, notes: 'Foot placement high & wide', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Face Pulls', sets: 3, repsMin: 15, repsMax: 20, restSeconds: 60, notes: 'External rotation at top', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'isolation' },
      { name: 'Plank', sets: 3, repsMin: 30, repsMax: 60, restSeconds: 60, notes: 'Hold (reps = seconds)', muscleGroup: 'lower', bodyPart: 'Core', category: 'isolation' },
    ],
    'full-c': [
      { name: 'Goblet Squat', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 120, notes: 'DB held at chest', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'DB Flat Press', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 120, notes: 'Full ROM', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'Seated Cable Row', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: 'Squeeze at contraction', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'Walking Lunges', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: 'DBs in hand (per leg)', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Hammer Curls', sets: 2, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Brachialis focus', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
      { name: 'Hanging Leg Raise', sets: 3, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Control the movement', muscleGroup: 'lower', bodyPart: 'Core', category: 'isolation' },
    ],
  },
  sessionNames: {
    'full-a': 'Full Body A',
    'full-b': 'Full Body B',
    'full-c': 'Full Body C',
  },
  weeklySchedule: {
    Sunday: 'full-a',
    Monday: 'rest',
    Tuesday: 'full-b',
    Wednesday: 'rest',
    Thursday: 'full-c',
    Friday: 'rest',
    Saturday: 'rest',
  },
};

// ── Intermediate Upper/Lower 4x/week (default) ──
const INTERMEDIATE_UPPER_LOWER: ProgramTemplate = {
  id: 'intermediate-upper-lower-4x',
  name: 'Upper/Lower 4x/Week',
  description: 'Balanced upper/lower split with strength and volume days',
  daysPerWeek: 4,
  goal: 'muscle_gain',
  experience: 'intermediate',
  equipment: 'full_gym',
  sessions: {}, // Uses the hardcoded default
  sessionNames: {},
  weeklySchedule: {
    Sunday: 'upper-a',
    Monday: 'lower-a',
    Tuesday: 'rest',
    Wednesday: 'upper-b',
    Thursday: 'lower-b',
    Friday: 'rest',
    Saturday: 'rest',
  },
};

// ── Advanced PPL 6x/week ──
const ADVANCED_PPL: ProgramTemplate = {
  id: 'advanced-ppl-6x',
  name: 'Push/Pull/Legs 6x/Week',
  description: 'High-frequency PPL split for advanced lifters',
  daysPerWeek: 6,
  goal: 'muscle_gain',
  experience: 'advanced',
  equipment: 'full_gym',
  sessions: {
    'push': [
      { name: 'Barbell Bench Press', sets: 4, repsMin: 6, repsMax: 8, restSeconds: 180, notes: 'Compound strength driver', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'DB Overhead Press', sets: 3, repsMin: 8, repsMax: 10, restSeconds: 120, notes: 'Seated', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'compound' },
      { name: 'Incline DB Press', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: '30° angle', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'Cable Fly (Low-to-High)', sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Constant tension', muscleGroup: 'upper', bodyPart: 'Chest', category: 'isolation' },
      { name: 'DB Lateral Raise', sets: 4, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Controlled, no momentum', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'isolation' },
      { name: 'Cable Overhead Tricep Extension', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Long head emphasis', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
      { name: 'Tricep Rope Pushdown', sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Split at bottom', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
    ],
    'pull': [
      { name: 'Barbell Deadlift', sets: 3, repsMin: 5, repsMax: 6, restSeconds: 180, notes: 'Conventional or sumo', muscleGroup: 'lower', bodyPart: 'Back', category: 'compound' },
      { name: 'Wide-Grip Lat Pulldown', sets: 4, repsMin: 8, repsMax: 12, restSeconds: 120, notes: 'Pull to upper chest', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'Chest-Supported DB Row', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: 'Zero lower back stress', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'Face Pulls', sets: 3, repsMin: 15, repsMax: 20, restSeconds: 60, notes: 'External rotation at top', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'isolation' },
      { name: 'Barbell Curl', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 60, notes: 'Strict form', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
      { name: 'Hammer Curls', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Brachialis focus', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
    ],
    'legs': [
      { name: 'Barbell Back Squat', sets: 4, repsMin: 6, repsMax: 8, restSeconds: 180, notes: 'Below parallel', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Romanian Deadlift', sets: 3, repsMin: 8, repsMax: 10, restSeconds: 150, notes: 'Feel hamstring stretch', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Leg Press', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 120, notes: 'Foot placement high & wide', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Leg Extension', sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Squeeze at top', muscleGroup: 'lower', bodyPart: 'Legs', category: 'isolation' },
      { name: 'Lying Leg Curl', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Slow eccentric', muscleGroup: 'lower', bodyPart: 'Legs', category: 'isolation' },
      { name: 'Standing Calf Raise', sets: 4, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Full ROM', muscleGroup: 'lower', bodyPart: 'Legs', category: 'isolation' },
      { name: 'Hanging Leg Raise', sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Control the movement', muscleGroup: 'lower', bodyPart: 'Core', category: 'isolation' },
    ],
  },
  sessionNames: {
    push: 'Push',
    pull: 'Pull',
    legs: 'Legs',
  },
  weeklySchedule: {
    Sunday: 'push',
    Monday: 'pull',
    Tuesday: 'legs',
    Wednesday: 'push',
    Thursday: 'pull',
    Friday: 'legs',
    Saturday: 'rest',
  },
};

// ── Home Dumbbell Program ──
const HOME_DUMBBELL: ProgramTemplate = {
  id: 'home-dumbbell-3x',
  name: 'Home Dumbbell 3x/Week',
  description: 'Effective full-body training with just dumbbells and a bench',
  daysPerWeek: 3,
  goal: 'muscle_gain',
  experience: 'beginner',
  equipment: 'home_dumbbells',
  sessions: {
    'home-a': [
      { name: 'Goblet Squat', sets: 3, repsMin: 10, repsMax: 15, restSeconds: 90, notes: 'DB held at chest', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'DB Flat Press', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 90, notes: 'Floor press if no bench', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'DB One-Arm Row', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Brace on bench or chair', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'DB Overhead Press', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 90, notes: 'Seated or standing', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'compound' },
      { name: 'DB Romanian Deadlift', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: 'Feel hamstring stretch', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'DB Bicep Curl', sets: 2, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Alternating', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
    ],
    'home-b': [
      { name: 'DB Lunges', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: 'Per leg, alternating', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'DB Incline Press', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 90, notes: 'Prop bench or pillows', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'DB Bent-Over Row', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Both arms, hinge at hips', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'DB Lateral Raise', sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Light weight, controlled', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'isolation' },
      { name: 'DB Sumo Squat', sets: 3, repsMin: 12, repsMax: 15, restSeconds: 90, notes: 'Wide stance, DB between legs', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'DB Tricep Kickback', sets: 2, repsMin: 12, repsMax: 15, restSeconds: 60, notes: 'Squeeze at top', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
    ],
    'home-c': [
      { name: 'DB Step-Ups', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: 'Use sturdy chair or bench', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'DB Floor Fly', sets: 3, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Slight bend in elbows', muscleGroup: 'upper', bodyPart: 'Chest', category: 'isolation' },
      { name: 'DB Pullover', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: 'Lats and chest stretch', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'DB Arnold Press', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 90, notes: 'Rotate as you press', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'compound' },
      { name: 'DB Hammer Curls', sets: 2, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Neutral grip', muscleGroup: 'upper', bodyPart: 'Arms', category: 'isolation' },
      { name: 'Plank', sets: 3, repsMin: 30, repsMax: 60, restSeconds: 60, notes: 'Hold (reps = seconds)', muscleGroup: 'lower', bodyPart: 'Core', category: 'isolation' },
    ],
  },
  sessionNames: {
    'home-a': 'Home Full Body A',
    'home-b': 'Home Full Body B',
    'home-c': 'Home Full Body C',
  },
  weeklySchedule: {
    Sunday: 'home-a',
    Monday: 'rest',
    Tuesday: 'home-b',
    Wednesday: 'rest',
    Thursday: 'home-c',
    Friday: 'rest',
    Saturday: 'rest',
  },
};

// ── Bodyweight Program ──
const BODYWEIGHT: ProgramTemplate = {
  id: 'bodyweight-3x',
  name: 'Bodyweight 3x/Week',
  description: 'No equipment needed — build strength and muscle with calisthenics',
  daysPerWeek: 3,
  goal: 'muscle_gain',
  experience: 'beginner',
  equipment: 'bodyweight',
  sessions: {
    'bw-a': [
      { name: 'Push-Ups', sets: 4, repsMin: 10, repsMax: 20, restSeconds: 60, notes: 'Full ROM, chest to floor', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'Bodyweight Squat', sets: 4, repsMin: 15, repsMax: 25, restSeconds: 60, notes: 'Below parallel', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Inverted Row (Table)', sets: 3, repsMin: 8, repsMax: 15, restSeconds: 60, notes: 'Under a sturdy table', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'Pike Push-Ups', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 60, notes: 'Shoulder focus', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'compound' },
      { name: 'Glute Bridge', sets: 3, repsMin: 15, repsMax: 20, restSeconds: 60, notes: 'Squeeze at top', muscleGroup: 'lower', bodyPart: 'Legs', category: 'isolation' },
      { name: 'Plank', sets: 3, repsMin: 30, repsMax: 60, restSeconds: 60, notes: 'Hold (reps = seconds)', muscleGroup: 'lower', bodyPart: 'Core', category: 'isolation' },
    ],
    'bw-b': [
      { name: 'Diamond Push-Ups', sets: 3, repsMin: 8, repsMax: 15, restSeconds: 60, notes: 'Tricep emphasis', muscleGroup: 'upper', bodyPart: 'Arms', category: 'compound' },
      { name: 'Bulgarian Split Squat', sets: 3, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Rear foot on chair (per leg)', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Superman Hold', sets: 3, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Back extension on floor', muscleGroup: 'upper', bodyPart: 'Back', category: 'isolation' },
      { name: 'Decline Push-Ups', sets: 3, repsMin: 8, repsMax: 15, restSeconds: 60, notes: 'Feet elevated on chair', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'Wall Sit', sets: 3, repsMin: 30, repsMax: 60, restSeconds: 60, notes: 'Hold (reps = seconds)', muscleGroup: 'lower', bodyPart: 'Legs', category: 'isolation' },
      { name: 'Mountain Climbers', sets: 3, repsMin: 20, repsMax: 30, restSeconds: 60, notes: 'Per side, fast pace', muscleGroup: 'lower', bodyPart: 'Core', category: 'compound' },
    ],
    'bw-c': [
      { name: 'Wide Push-Ups', sets: 3, repsMin: 10, repsMax: 20, restSeconds: 60, notes: 'Chest emphasis', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'Jump Squats', sets: 3, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Explosive, soft landing', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Inverted Row (Table)', sets: 3, repsMin: 8, repsMax: 15, restSeconds: 60, notes: 'Wider grip for back width', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'Lateral Lunges', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Per side, push off heel', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Tricep Dips (Chair)', sets: 3, repsMin: 10, repsMax: 15, restSeconds: 60, notes: 'Hands on chair edge', muscleGroup: 'upper', bodyPart: 'Arms', category: 'compound' },
      { name: 'Bicycle Crunches', sets: 3, repsMin: 20, repsMax: 30, restSeconds: 60, notes: 'Per side, controlled', muscleGroup: 'lower', bodyPart: 'Core', category: 'isolation' },
    ],
  },
  sessionNames: {
    'bw-a': 'Bodyweight A',
    'bw-b': 'Bodyweight B',
    'bw-c': 'Bodyweight C',
  },
  weeklySchedule: {
    Sunday: 'bw-a',
    Monday: 'rest',
    Tuesday: 'bw-b',
    Wednesday: 'rest',
    Thursday: 'bw-c',
    Friday: 'rest',
    Saturday: 'rest',
  },
};

// ── Fat Loss Program ──
const FAT_LOSS_CIRCUIT: ProgramTemplate = {
  id: 'fat-loss-circuit-4x',
  name: 'Fat Loss Circuit 4x/Week',
  description: 'High-intensity circuits combining strength and cardio for maximum calorie burn',
  daysPerWeek: 4,
  goal: 'fat_loss',
  experience: 'intermediate',
  equipment: 'full_gym',
  sessions: {
    'circuit-a': [
      { name: 'Barbell Front Squat', sets: 4, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Superset with next', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Push-Ups', sets: 4, repsMin: 15, repsMax: 20, restSeconds: 60, notes: 'Superset with squat', muscleGroup: 'upper', bodyPart: 'Chest', category: 'compound' },
      { name: 'DB Row', sets: 3, repsMin: 12, repsMax: 15, restSeconds: 45, notes: 'Per arm, fast pace', muscleGroup: 'upper', bodyPart: 'Back', category: 'compound' },
      { name: 'Kettlebell Swing', sets: 3, repsMin: 15, repsMax: 20, restSeconds: 45, notes: 'Hip hinge, explosive', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Battle Ropes', sets: 3, repsMin: 20, repsMax: 30, restSeconds: 45, notes: '30 seconds per set', muscleGroup: 'upper', bodyPart: 'Other', category: 'compound' },
      { name: 'Plank', sets: 3, repsMin: 45, repsMax: 60, restSeconds: 30, notes: 'Hold (reps = seconds)', muscleGroup: 'lower', bodyPart: 'Core', category: 'isolation' },
    ],
    'circuit-b': [
      { name: 'Barbell Deadlift', sets: 4, repsMin: 8, repsMax: 10, restSeconds: 90, notes: 'Heavy compound', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'DB Overhead Press', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Standing', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'compound' },
      { name: 'Box Jumps', sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60, notes: 'Explosive, step down', muscleGroup: 'lower', bodyPart: 'Legs', category: 'compound' },
      { name: 'Cable Face Pull', sets: 3, repsMin: 15, repsMax: 20, restSeconds: 45, notes: 'External rotation', muscleGroup: 'upper', bodyPart: 'Shoulders', category: 'isolation' },
      { name: 'Mountain Climbers', sets: 3, repsMin: 20, repsMax: 30, restSeconds: 30, notes: 'Per side, fast', muscleGroup: 'lower', bodyPart: 'Core', category: 'compound' },
      { name: 'Burpees', sets: 3, repsMin: 8, repsMax: 12, restSeconds: 60, notes: 'Full extension at top', muscleGroup: 'lower', bodyPart: 'Other', category: 'compound' },
    ],
  },
  sessionNames: {
    'circuit-a': 'Circuit A — Upper Focus',
    'circuit-b': 'Circuit B — Lower Focus',
  },
  weeklySchedule: {
    Sunday: 'circuit-a',
    Monday: 'rest',
    Tuesday: 'circuit-b',
    Wednesday: 'rest',
    Thursday: 'circuit-a',
    Friday: 'circuit-b',
    Saturday: 'rest',
  },
};

// ── Template Registry ──

export const PROGRAM_TEMPLATES: ProgramTemplate[] = [
  BEGINNER_FULL_BODY,
  INTERMEDIATE_UPPER_LOWER,
  ADVANCED_PPL,
  HOME_DUMBBELL,
  BODYWEIGHT,
  FAT_LOSS_CIRCUIT,
];

/**
 * Find the best matching program template based on user profile.
 * Scoring: exact match on each dimension = 1 point, closest wins.
 */
export function findBestTemplate(
  goal: string,
  experience: string,
  equipment: string,
): ProgramTemplate {
  let bestScore = -1;
  let bestTemplate = PROGRAM_TEMPLATES[0];

  for (const t of PROGRAM_TEMPLATES) {
    let score = 0;
    // Equipment is most important — can't do barbell exercises without a gym
    if (equipment === 'bodyweight' && t.equipment === 'bodyweight') score += 3;
    else if (equipment === 'home_dumbbells' && t.equipment === 'home_dumbbells') score += 3;
    else if (equipment === 'full_gym' && t.equipment === 'full_gym') score += 3;
    else if (equipment === 'full_gym' && t.equipment !== 'bodyweight') score += 1;

    // Experience level
    if (experience === t.experience) score += 2;
    else if (
      (experience === 'intermediate' && t.experience === 'beginner') ||
      (experience === 'advanced' && t.experience === 'intermediate')
    ) score += 1;

    // Goal
    if (goal === t.goal) score += 1;

    if (score > bestScore) {
      bestScore = score;
      bestTemplate = t;
    }
  }

  return bestTemplate;
}

// ── Program Progression & History ────────────────────────────

const PROGRAM_HISTORY_KEY = '@program_history_v1';

export interface ProgramHistoryEntry {
  program: CustomProgram;
  archivedAt: string;
}

/**
 * Archive a completed program to history.
 */
export async function archiveProgram(program: CustomProgram): Promise<void> {
  try {
    const raw = await AsyncStorage.getItem(PROGRAM_HISTORY_KEY);
    const history: ProgramHistoryEntry[] = raw ? JSON.parse(raw) : [];
    history.unshift({
      program: { ...program, completedAt: program.completedAt || new Date().toISOString() },
      archivedAt: new Date().toISOString(),
    });
    // Keep last 20 programs
    await AsyncStorage.setItem(PROGRAM_HISTORY_KEY, JSON.stringify(history.slice(0, 20)));
  } catch {}
}

/**
 * Load program history.
 */
export async function loadProgramHistory(): Promise<ProgramHistoryEntry[]> {
  try {
    const raw = await AsyncStorage.getItem(PROGRAM_HISTORY_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

/**
 * Check if the current program has expired (past its durationWeeks).
 * Returns the number of weeks elapsed and whether the program is complete.
 */
export function getProgramProgress(program: CustomProgram): {
  weeksElapsed: number;
  totalWeeks: number;
  isComplete: boolean;
  daysRemaining: number;
  percentComplete: number;
} {
  const totalWeeks = program.durationWeeks ?? 4;
  const startDate = new Date(program.createdAt);
  const now = new Date();
  const msElapsed = now.getTime() - startDate.getTime();
  const daysElapsed = Math.floor(msElapsed / (1000 * 60 * 60 * 24));
  const weeksElapsed = Math.floor(daysElapsed / 7);
  const totalDays = totalWeeks * 7;
  const daysRemaining = Math.max(0, totalDays - daysElapsed);
  const percentComplete = Math.min(100, Math.round((daysElapsed / totalDays) * 100));
  const isComplete = daysElapsed >= totalDays;

  return { weeksElapsed, totalWeeks, isComplete, daysRemaining, percentComplete };
}

/**
 * Suggest the next program based on the completed program and user profile.
 * Progression logic:
 * - Beginner → Intermediate (after completing beginner program)
 * - Intermediate → Advanced (if goal is muscle_gain)
 * - Fat loss → Muscle gain intermediate (after fat loss phase)
 * - Same level → Repeat with note to increase weights
 */
export function suggestNextProgram(
  currentProgram: CustomProgram,
  goal: string,
  experience: string,
  equipment: string,
): { template: ProgramTemplate; reason: string } {
  // Find current template
  const currentTemplate = PROGRAM_TEMPLATES.find(t => t.name === currentProgram.name);
  const currentExp = currentTemplate?.experience || experience;
  const currentEquip = currentTemplate?.equipment || equipment;

  // Progression rules
  let nextExp = currentExp;
  let nextGoal = goal;
  let reason = '';

  if (currentExp === 'beginner') {
    nextExp = 'intermediate';
    reason = 'You\'ve completed your beginner program. Time to level up with more volume and frequency.';
  } else if (currentExp === 'intermediate' && goal === 'muscle_gain') {
    nextExp = 'advanced';
    reason = 'You\'re ready for higher frequency training. This PPL split maximises muscle growth.';
  } else if (currentTemplate?.goal === 'fat_loss') {
    nextGoal = 'muscle_gain';
    reason = 'Great work on the fat loss phase. Now let\'s build muscle with a structured split.';
  } else {
    // Same level — suggest repeating with progression
    reason = 'Repeat this mesocycle with 5-10% heavier weights. Progressive overload is the key.';
    return { template: currentTemplate || PROGRAM_TEMPLATES[0], reason };
  }

  const nextTemplate = findBestTemplate(nextGoal, nextExp, currentEquip);
  return { template: nextTemplate, reason };
}

/**
 * Convert a ProgramTemplate into a CustomProgram and save it.
 * Also updates the schedule store.
 */
export async function applyProgramTemplate(template: ProgramTemplate): Promise<CustomProgram> {
  // Archive current program before switching
  const existing = await loadCustomProgram();
  if (existing) {
    await archiveProgram(existing);
  }

  const program: CustomProgram = {
    name: template.name,
    description: template.description,
    sessions: template.sessions,
    sessionNames: template.sessionNames,
    sessionColors: Object.fromEntries(
      Object.keys(template.sessionNames).map((key, i) => [key, SESSION_COLORS_POOL[i % SESSION_COLORS_POOL.length]])
    ),
    weeklySchedule: template.weeklySchedule,
    createdAt: new Date().toISOString(),
    generatedByZaki: false,
    durationWeeks: 4,
  };

  // Save the custom program
  await saveCustomProgram(program);

  // Also update the schedule store so the Home screen reflects the new schedule
  const schedule = buildFullSchedule(template.weeklySchedule as Partial<Record<DayName, SessionType>>);  // DayName imported at top
  await applyScheduleWithHistory({
    appliedAt: new Date().toISOString(),
    description: `Applied program: ${template.name}`,
    schedule,
    appliedByZaki: false,
  });

  return program;
}
